### ISSUE TITLE
SoS convert not rendering ToC properly / failing silently 

### ISSUE THREAD

**Issue by j-andrews7** [vatlab/sos-notebook#107]
I have a very large ipynb notebook using the SoS and R kernels that seems to be giving the `sos convert` command issues. 

When I try to convert to html via `sos convert CTCL_Analyses.ipynb CTCL_Analyses.html --template sos-report-toc` I get a warning but it still writes the file:
```
[NbConvertApp] Converting notebook /mnt/e/CTCL/CTCL_Analyses.ipynb to html
/home/jared/anaconda3/envs/py3/lib/python3.6/site-packages/nbconvert/filters/datatypefilter.py:41: UserWarning: Your element with mimetype(s) dict_keys([]) is not able to be represented.
  mimetypes=output.keys())
[NbConvertApp] Writing 29911377 bytes to /mnt/e/CTCL/CTCL_Analyses.html
INFO: Output saved to CTCL_Analyses.html
```

However, the resulting `html` file ToC doesn't match that of the ToC in the notebook - upper level headers are left out (those starting with #). Does it only allow for one level of nesting, i.e. is my having several levels of headers causing issues?

I am also unable to save in the `.sos` format using either the File -> Download As or `sos convert` methods. No errors, but the file only has the SoS format header and no content. I can report this as a separate issue if wanted.

I'm running sos 0.9.16.3, python 3.6.2, and jupyter 4.4.0.

**Comment by BoPeng** [comment]
Is it possible for you to send a minimal example that demonstrate the problem? You can try to cut the notebook in half repeatedly until problem disappears, then remove output etc...

**Comment by BoPeng** [comment]
Also, do you see any problem if you do a direct `ipynb` to `html` conversion with command `jupyter convert` ?

**Comment by j-andrews7** [comment]
No, the html renders fine, it's just the ToC that doesn't seem to behave correctly. My highest level headers (#) don't show, but the next level of headers (##) expand as expected. I don't know if I am just expecting something that isn't happening by design or if it's an actual error.

I've attached a much shorter notebook as an example - both the html and ipynb file are included. I usually use the highest level header (#) to differentiate sections, then another level with subsections. Preferably, they'd all show up/be nested in the ToC, but I can always just use the (##) header as my section headers and just accept that I won't have the highest level of nesting that I'd want.

This file also doesn't convert properly to SoS for me - I've also attached the `.sos` file I get when I try to convert it. No errors are thrown.
[CTCL_Analyses-Copy1.zip](https://github.com/vatlab/sos-notebook/files/2284714/CTCL_Analyses-Copy1.zip)

Thanks for such a quick response.

**Comment by BoPeng** [comment]
For the TOC, the logic is that people usually use `#` for the title of the report, and `##` etc for section, subsections. Since there is only one title that will always be at the beginning of the report, including `#` in TOC would not help much on navigation, but will increase indentation and will not look good if the title is long. Since you are using R, do you know how RStudio handles TOC in its HTML output?

For converting to `.sos`, the `.sos` format is intended for embedded sos workflow. That is to say, it will only include cells in SoS kernel and with`[]` headers. There is an option `--all` to save most input to plain text format (not necessarily a valid sos workflow), but it was a (failed) attempt to save notebook for version control purposes. With tools such as [nbstripout](https://github.com/kynan/nbstripout) and [nbdime](https://github.com/jupyter/nbdime), I have found it unnecessary and might get rid of it later on.

**Comment by j-andrews7** [comment]
Thanks for the clarification. I don't know how RStudio handles it, but I assume it's likely similar. I will just adjust my scheme a bit then.

As for the `.sos` stuff, that makes sense. I was just trying to convert to it in an attempt to see if the `sos-html` convert command would yield any different result - guess I didn't read up enough on it.

I'm going to change the title of this to a more descriptive question regarding ToC levels and close it - thanks for your patience and help.

**Comment by BoPeng** [comment]
Thanks. These feedbacks are always helpful. I am creating a separate ticket for this.
