### ISSUE TITLE
Control figure size in %preview

### ISSUE THREAD

**Issue by gaow** [vatlab/sos-notebook#124]
Not sure if we've discussed this, but for a high resolution figure previewed in a notebook, it usually occupies so much space that looks very distracting on the HTML report generated. I wonder if there can be some way to pass parameters such as --width / --height that takes a scaling factor to scale the figure in preview.

**Comment by j-andrews7** [comment]
I would second this, as on a somewhat related note I sometimes have issues previewing PDFs with different size images in them. Usually the issue arises with different width images - it seems to display at the lowest width in the PDF for all images. See example below:

Narrowest image displays fine:
![image](https://user-images.githubusercontent.com/10225716/47024887-31d8f800-d128-11e8-8e81-f40b293b1ad5.png)

Wider image gets cut off at about the same width as the narrow image (it should have 6 columns):
![image](https://user-images.githubusercontent.com/10225716/47024963-503ef380-d128-11e8-986c-e9ce5491490b.png)

**Comment by BoPeng** [comment]
Any suggestion? The `%preview` magic supports additional options so perhaps something like `--width 800pt` would work?

**Comment by gaow** [comment]
Not sure if it should be px or a percentage. Percentage is intuitive. Am in the airport now. Sorry if I cannot follow up on the discussion

**Comment by j-andrews7** [comment]
Yeah, I would take either. px or pt might be easier to implement/use with vector graphics though.

**Comment by BoPeng** [comment]
The sos-notebook trunk does not work quite well with the sos trunk which has just undergone a major internal implementation change. I will take care of this once the dust settles.

**Comment by BoPeng** [comment]
Please test. Need the latest trunk of sos and sos-notebook.

![image](https://user-images.githubusercontent.com/9889312/47400934-d6e56900-d704-11e8-919d-38478d098a67.png)

**Comment by BoPeng** [comment]
Sorry, it currently only works for "images" (jpg, png etc), not for pdf. It should be easy to add though. Let me check.

**Comment by BoPeng** [comment]
Please update  to sos 0.17.1 and try again. (`pip install sos -U`).

**Comment by j-andrews7** [comment]
The width and height options work now, but I'm still having issues with larger pages within the PDF followed by smaller pages being cut off as shown above. I can e-mail you such a PDF if you'd like one for testing.

Also, the resolution takes a pretty big hit - is there any way to utilize the sizing in the conversion from PDF to PNG to retain the DPI rather than just scaling the PNG afterwards? Again, I say this having basically no idea of how that process works under the hood. Thanks for taking the time to improve this - you all are definitely the most responsive and engaged devs I've interacted with in the realm of bioinformatics, and it's not even close.

**Comment by BoPeng** [comment]
@j-andrews7 Please upload the PDF here or PM to bpeng@mdanderson.org if preferred.

SoS uses the "default resolution" to convert PDF to png for preview, which should look ok in standard size, but can look bad with large specified `--with`. Let me check what I can do here.

**Comment by BoPeng** [comment]
This appear to be a bug with imagemagick/wand... please try again from the trunk of sos, or wait for the next sos release.

**Comment by BoPeng** [comment]
I have
1. Changed the default `iframe` preview to `object` preview, which works much better at least in chrome. `--with` etc works.
2. Fixed the bug that caused images to be cut off.
3. Increased default dpi from 72 to 150 for png preview, and added option `--dpi` to allow higher or lower resolution.
4. Released sos 0.17.2 with these changes.

Let me know if everything works so that I can close the ticket.

**Comment by j-andrews7** [comment]
Works perfectly. Thanks!
