### ISSUE TITLE
Variable exchange between workflow steps / kernels within workflow

### ISSUE THREAD

**Issue by sybrnorox** [vatlab/sos-notebook#161]
Hi there, 

first of all great project, I am enjoying it a lot. I am using it to do data analysis in R and Python in a single Notebook environment.  However, I feel like I am missing something here. Why is it not possible to pass variables among workflow steps or between kernels in one workflow, for that matter.

For example, I have a notebook, with say 10 cells. In one case I want to run only Cells, 1,2 and 10, in another case I want to run them all. Putting a header in each cell according to these two workflow parts and then just having two cells at the end to run the individual workflows seems like a really good idea to me. The output should of course just be shown in my notebook the same as it would be if I ran the cells manually by Shift+Enter.

The following is a simpler example, but I think it highlights what I am looking for:

```
[1]
R:
      test <- 5+5
```

```
[2]
output: test2
R:
      test2 <- test + 5
```

```
[3]
input: test2
output: test3
Python3:
       test3 = test2
```

```
[4]
input: test3
julia-1.0:
      test4 = test3+2
      print(test4)
```

I think it's obvious what this is supposed to do. I am expectuing the two R steps to run in the same kernel and therefore dont need to define input and output for their communication. In my understanding here 'output' is basically %put to the SoS kernel and 'input' %gets variables from SoS kernel. The four code snippets would all be individual cells that I could run by a call to `%sosrun test`. 

To me this is how I would expect workflows to work within the SoS Notebook framework of combining multiple kernels. This way I would really not worry about pipelining stuff at all, because my cretive notebook is a fully functional pipeline.

I can of course achieve this by running my code only on set conditions (like having a bool if clause for a section to decide wehther I want to run it this time). But that does not work for %get or %put magics. If the variables dont exist because I decided not to run the cells in which they are defined %get-ing them will throw an error and interrupt notebook execution.

But I feel, what I am looking for is just not what this is supposed to do, right? I see how the workflow system is designed, but for most cases in my work it is way too tedious to write all results to a file and then read them into the next workflow step.

Please tell me I am overlooking something essential.

Cheers,
Jan

**Comment by BoPeng** [comment]
Technically speaking, when you add section headers to the scripts, you have left `SoS Notebook` and entered the realms of `SoS Workflow` where the execution of workflows are outside of SoS Notebook, without the help of the SoS kernel, without subkernels, and therefore no `%get` and `%put` magics. The idea of analyzing data in subkernels with data exchange, and translate scripts into workflows have been explained in details in, for example, my [JupyterCon talk](https://github.com/vatlab/JupyterCon2018), from page 22 to 23 in the slides.

What you want essentially would be exchanging data in workflow mode, which has been discussed a lot. Therefore two potential solutions:

1. On the SoS Notebook side, is it possible to execute cells in a workflow fashion with some magics? That is to say, we keep the SoS kernel, keep the subkernels, keep the `%get` magic, and instead of executing cells interatively or sequentially (e.g. `Run All`), we find some way to execute multiple cells together.

2. On the SoS Workflow side, is it possible to `%get` variables between workflow steps? If you think of it, it is extremely difficult to exchange data between two languages without the help of a third-party, especially when there is no living instances (kernels) of the languages. We have talked about a [DataBus](https://github.com/vatlab/SoS-DataBus) kind of mechanism to achieve this but the project is at the planning stage.

So I would say technically speaking 1 is easier than 2 but it would make things a lot more complicated on the notebook side, and we donot yet have a good design for 2 yet.

**Comment by sybrnorox** [comment]
Thanks a lot for the detailed reply. I am very much looking forward to future developments of SoS on a whole!
