### ISSUE TITLE
Jupyter Lab support

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos-notebook#17]
This is something we have avoided for a while but since the whole community is moving away from Jupyter to JupyterLab, we have to address it one way of another. Here are my observations:

Pros of JupyterLab:
1. Tabs are nice, both notebook tabs and side panel tabs.
2. A terminal is really nice.
3. Much better GUI compare to Jupyter.
4. Has something like image viewer and inspector, although not sure how it works.

Cons of JupyterLab: (Correct me if I am wrong)
1. Does not have the scratchpad style side panel
2. Does not support multiple languages in one notebook.
3. Does not support inline expression (our `%render` magic)
4. Does not support line-by-line execution

Other points:
1. Jupyter is still being maintained and will likely exist for a long time, so SoS will keep up at least with Jupyter development.
2. JupyterLab is new development of Jupyter with better GUI but does not address any of the problems that SoS is trying to address (multi-kernel notebook).

It might be relatively easy to have a stripped down version of SoS notebook to work with JupyterLab, that is essentially a Python3.6 kernel that supports SoS workflow engine. Even then, it is awkward to be able to open SoS notebooks in JupyterLab but not able to work with it.

**Comment by gaow** [comment]
When confronted, I think we can certainly mention that Jupyter Lab is future direction.  SoS Notebook does have a panel-like GUI but it is not the same concept as Jupyter Lab. Just like SoS Notebook made Jupyter notebook better, future SoS will make Jupyter Lab better. We do not implement it right away because Jupyter Lab is not yet popular and a lot changes will happen before it finally settles.
