### ISSUE TITLE
"UndefVarError: whos not defined" error

### ISSUE THREAD

**Issue by arthurod91** [vatlab/sos-notebook#205]
Dr. Bo Peng,

I'm using SoS kernel in a Julia 1.1 + Python 3 environment. Although I've had no problems with the things I'm doing right now I keep getting the `UndefVarError: whos not defined` sometimes after the execution of Julia cells, sometimes after the execution of Python cells.

I've done a little research and I think it is because `Base.whos()` method from Julia 0.x no longer works in Julia 1.x, the similar method is `Base.varinfo()`, and probably the sos-julia extension has not been updated with that. I tried to do some tweaking by myself but I couldn't fix it, and it gets me a little worried that it can become a major issue for me in some projects I'm planning to do in the near future.

Thank you in advance for taking a look!

**Comment by BoPeng** [comment]
We are [aware of the bug](https://github.com/vatlab/sos-julia/issues/7). We have fixed it but did not release it because the only guy who knows Julia left our team and we could not test the module thoroughly. Anyway, I have just release `sos-julia` 0.18.2, please test and let us know if you notice any problem.

**Comment by arthurod91** [comment]
>  I have just released sos-julia 0.18.2

Thank you very much doctor!!! I'm testing it and indeed, it doesn't have that bug. Sure I will let you know if I notice something else.
