### ISSUE TITLE
Compatibility with papermill

### ISSUE THREAD

**Issue by ktaletsk** [vatlab/sos-notebook#245]
I am researching compatibility of SoS notebooks with `papermill`. Papermill is a tool for parameterizing and executing Jupyter Notebooks.

I am researching the simplest case: notebook with no parameters. In this case I expect papermill to be able to execute notebook top-to-bottom using whatever kernel it uses. When running without parameters, papermill does not need to be aware of language details of particular kernels. I tried multiple language kernels and they worked fine: Python, R, Java, Scala, Octave, C++, Javascript, Typescript. 

However, when I create SoS notebook and run it through papermill, it has multiple problems:
- Warning message below each cell: `Frontend communicator is broken. Please restart jupyter server`
- Cells are executed as if they are all using SoS subkernel, effectively ignoring chosen subkernel.

This example should have worked, but it did not:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/8834829/64558379-5540fe80-d309-11e9-8957-7bdd26244b0f.png">

This example should not have worked, but it did:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/8834829/64558437-773a8100-d309-11e9-833e-96946224b3fd.png">

I wonder if problem is in papermill or sos-notebook and what can be done to fix it?

**Comment by BoPeng** [comment]
I am not at all familiar with papermill but this is related to #112 and #128 for batch execution of sos notebooks, and I have commented on the issue at https://github.com/vatlab/sos-notebook/issues/112#issuecomment-514892958 . Basically, 

1. The SoS kernel needs meta information from the frontend to know the kernel of each cell. The notebook will not be executed correctly if papermill does not send such information to the kernel.
2. The SoS kernel needs some more information to execute magics. For example, the `%sosrun` magic executes workflows in the entire notebook, which requires the frontend to collect such information and send to the kernel. Papermill will never be able to do this if it sends the content of the cells one by one.
3. Even worse, SoS also allows things such as `%run &` to execute workflow in the background. The cell will return immediately but the output could be appended slowly to the right cell. These behaviors require the assistance of customized communication channel that papermill cannot provide.

All these have caused problems to the `nbconvert --execute` mechanism. It could be fixed but require a lot of effort so I now tend more to a hidden browser approach for batch execution. Basically the entire frontend will be created in a hidden browser (using selenium) so that all frontend components could be there for the batch execution of the notebook.

So the bottom line is that papermill will not work with SoS Notebook. A PR to papermill might solve the first issue (passing kernel information) but I suppose there is no way to fix the latter two issue.
