### ISSUE TITLE
Kernel dies after interruption

### ISSUE THREAD

**Issue by zemlyansky** [vatlab/sos-notebook#261]
When interrupting some long running process, SoS and all its active kernels die. 

For example, starting this in Python 3 kernel:
```
b = []
for a in range(1, 100000000):
    b.append(a * a)
```
then sending `Keyboard Interrupt` (stop button in Jupyter Notebooks) always shows `Kernel Restarting. The kernel appears to have died. It will restart automatically.` So all information is lost. A normal behavior would be to stop process without loosing the information stored in variables. Interrupting processes is important for machine learning. For example you can manually stop a model training if it doesn't show any improvement

sos-python (0.18.3)
sos-notebook (0.20.6)
python3 (3.7.4)

**Comment by BoPeng** [comment]
SoS is a superset of Python. Is the behavior more acceptable if you run the code in SoS cells and interrupt? This of course does not fix your problem, which happens because the signal interrupts SoS as well as the subkernals, and causes SoS to kill subkernel even if the subkernel catches the signal. It does not sound right for SoS to ignore the signal so let me think a bit more on a more reasonable behavior.

**Comment by zemlyansky** [comment]
Interruption of a SoS cell also throws the `The kernel appears to have died. It will restart automatically` error. Doing the same operation in a regular Python notebook (not Python cell of SoS notebook) shows:
```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-1-16e0871010ec> in <module>
      1 b = []
      2 for a in range(1, 100000000):
----> 3     b.append(a * a)

KeyboardInterrupt: 
```
But the main idea is that in Python notebook kernel continues working after interruption, all variables declared previously are available:
```
len(b) # -> 24190084
```

**Comment by BoPeng** [comment]
Thanks @zemlyansky for the report. It turns out this is a regression bug caused by some worker process clean up code from sos. I did notice it recently but did not get a chance to look into it. I have fixed the bug and adjusted the output of `KeyboardInterrupt` (showing trace back instead of just a message). Please update to sos and sos-notebook 0.20.7 and let me know if you notice any problem.

**Comment by zemlyansky** [comment]
Updated, then checked both Python3 and SoS kernels. No errors now. Thank you!

**Comment by BoPeng** [comment]
Great. Thanks again. At least this time we are adding a test for the interruption of kernels to make sure the bug does not come back again.

Feel free to let us know if you notice any further problem.
