### ISSUE TITLE
how to interrupt a sub kernel? 

### ISSUE THREAD

**Issue by kundeng** [vatlab/sos-notebook#284]
Can't find a way to interrupt the sub-kernel.

**Comment by BoPeng** [comment]
SoS receives the interruption signal and kills all subkernels and itself... which is what "interruption a Jupyter kernel" generally means. It might make sense to interrupt only the subkernel **if a subkernel is running**, and interrupt itself otherwise. In general the behavior is not well-defined though.

**Comment by BoPeng** [comment]
Note that if the kernel is not running, you can use magic `%shutdown --restart R` etc to restart a subkernel.

**Comment by BoPeng** [comment]
This is the current behavior. Namely, when the Python3 is in a dead loop, you do `Kernel -> Interrupt Kernel`, and the Python3 kernel will be killed, but SoS will continue running.

![image](https://user-images.githubusercontent.com/9889312/79459063-554c5f80-7fb8-11ea-96a8-3dbf0b07380f.png)

**Comment by BoPeng** [comment]
I think the problem here is that it is not easy to determine if sos or one of its subkernels is being interrupted.
