### ISSUE TITLE
please add markdown into the dropdown selection menu of sos. 

### ISSUE THREAD

**Issue by kundeng** [vatlab/sos-notebook#286]
I know shortcut, but it is convenient to have it there.

**Comment by BoPeng** [comment]
This sounds like a good idea but are you aware of https://github.com/vatlab/markdown-kernel ?

**Comment by BoPeng** [comment]
The biggest problem with `markdown-kernel` is the input is not hidden after it is evaluated. It is quite difficult to achieve this with classic jupyter but perhaps doable in Jupyter lab because lab has standard expand/collapse interface. Let me revisit https://github.com/vatlab/markdown-kernel/issues/2

**Comment by BoPeng** [comment]
`jupyterlab-sos` is now updated to automatically fold input of codecell with Markdown kernel.
