### ISSUE TITLE
possible bug - cell code selection dropdown does not appear in jupyterlab, but appear in notebook

### ISSUE THREAD

**Issue by rkuo** [vatlab/sos-notebook#299]
I am new on this.
I try to learn jupyter and other python related packages on a old iMac (os 10.12.6).  I installed jupyter with Anaconda and set a new environment python=3.7. I managed to get sos worked with notebook but not with jupyterlab (dropdown did not show). In one error message, it indicated I need to install Node version >10.  `node -v` returned v6.13.1. So, I did `conda install nodejs=13.13.0`  . The system asked me to rebuild lab `jupyter lab build`, it worked after new node version. 

The default version of nodejs used in jupyterlab may be too old.

**Comment by BoPeng** [comment]
This is a known issue, basically classic jupyter, because of its dependency on a remote package (`matplotlib_base` as far as I remember), depends on node < 10, but Jupyterlab depends on node >= 10.  There are ways to get around of this problem to have both installed (e.g. install classic jupyter, upgrade node without dependency checking, then install jupyterlab) but we generally recommend using jupyterlab only to avoid potential problems.

What makes things even more confusing is that anaconda is bundled with an earlier version of JupyterLab that requires node < 10.

**Comment by rkuo** [comment]
Thank you, I will avoid matplotlib for now.
