### ISSUE TITLE
Opening Notebook recognizes wrong kernel

### ISSUE THREAD

**Issue by step21** [vatlab/sos-notebook#333]
I have the general bash kernel installed (sos-bash) but when opening an old notebook, it always says it overrides it with calysto-bash (which is not installed). This is a fresh install. In the notebook file, I do not see any references to calysto-bash. Any ideas what this could be related to?

```
WARNING: Overriding kernel bash used by subkernel Bash with kernel calysto_bash.
```

**Comment by BoPeng** [comment]
Do you have a bash kernel installed? SoS will use any of the supported bash kernel, but will assume `calysto_bash` if you do not have any installed.

**Comment by step21** [comment]
`.local/share/jupyter/kernels` says I do, and the dropdown menu too.

**Comment by BoPeng** [comment]
Let me confirm the problem:

1. You have [`bash kernel`](https://github.com/takluyver/bash_kernel) installed.
2. You used this kernel for an old notebook.
3. You try to open the notebook, sos tries to use `calysto_bash`.

If not too troublesome, could you make a copy of your notebook, remove sensitive information (leaving only one cell that uses `bash`), attach it here, or PM to bo.peng@bcm.edu, so that I can try to reproduce the problem?

**Comment by BoPeng** [comment]
Thanks. I removed the warning message and release sos-notebook 0.22.8.
