### ISSUE TITLE
how to setup JupyterHub using SoS-Notebook

### ISSUE THREAD

**Issue by vibbits** [vatlab/sos-notebook#75]
Hi all, we are wondering how you would recommend to setup a JupyterHub when we would like to use a sos-notebook.

Is the mdabioinfo/sos-notebook image suited for this setup? 
Or is there an installation guideline of your JupyterHub at the institute?
In our case, we would eventually need to run a docker from the SoS Notebook in JupyterHub. 

Any hint on this matter would be interesting to know. Thanks a lot!

**Comment by BoPeng** [comment]
@ChrisWakefield knows more about our setup, but

1. We did not use the image because we used a RHEL virtual machine and installed all kernels manually.
2. @ChrisWakefield can help answer this.
3. Our sos/jupyterhub server does not support docker yet so we will have to use docker remotely now. We will test docker pretty soon though.

Our server is simply a regular JupyterHub server with sos installed. The installation of sos is almost trivial but it was troublesome to setup JupyterHub itself (mostly user authentication and automount of home directories) and kernels (anaconda `node.js` vs system `node.js` for Javascript etc). I would suggest that you start building a JupyterHub server and let us know if you have any specific questions.

**Comment by ChrisWakefield** [comment]
I think the installation steps are those already outlined at https://vatlab.github.io/sos-docs/#runningsos (Installing SoS locally)

We're getting the last bits of an installation script finalized, though this is what works internally for us and others may have their own peculiar requirements and constraints.  I expect to make the script public once it's complete and sanitized.  This installation script is basically the same as the link above with some extra consideration for local concerns and for dealing with having all options available at once.

If you're referring to running notebooks as Docker containers, I believe that would simply be https://github.com/jupyterhub/dockerspawner, which we are not currently using locally.
If instead you're referring to running some arbitrary docker container, one could have a bash (or some other) notebook/cell with commands to "docker run".

**Comment by ChrisWakefield** [comment]
@BoPeng ,
>> Is the mdabioinfo/sos-notebook image suited for this setup?
If this is something you created, we should ensure that the dockerfile to build it is available on docker hub.  (I don't see it.)  Without that, we can't see what is inside the image and whether it's applicable.

**Comment by BoPeng** [comment]
I regularly push this image to dockerhub and I can see this image from https://hub.docker.com/r/mdabioinfo/sos-notebook/ . I do not know if it is a good idea to spawn jupyter server inside docker because the extra layer of file system can be troublesome and because it does not have MATLAB and SAS, but I suppose this can be a good starting image if we decide to use dockerspawner.

**Comment by BoPeng** [comment]
The Dockerfile is available at https://github.com/vatlab/SoS/tree/master/development/docker-notebook , I did not know I need to link dockerbub there... Will try to figure it out later.

It is a not good idea to mess with nested docker containers so we should not use dockerspawner to start jupyter instances from JupyterHub if you aim to start docker from SoS notebooks. I suppose it is relatively easy to install JupyterHub on a server with docker but the server needs to be reasonably powerful to accommodate multiple docker instances from multiple users. If resources are available, perhaps you can experiment installations in cluster or distributed systems such as Kubernetes. 

Actually, I see [this presentation](https://indico.cern.ch/event/663264/contributions/2818482/attachments/1590916/2517924/EBocchi_CS3_Containers.pptx) from CERN when I research on JupyterHub installation. Perhaps you can learn even talk to them?

**Comment by vibbits** [comment]
Thanks again for the feedback - the CERN presentation looks very interesting - I've seen the readme from [Zero to JupyterHub](https://media.readthedocs.org/pdf/zero-to-jupyterhub-with-kubernetes/latest/zero-to-jupyterhub-with-kubernetes.pdf) - 
I will look into the stuff tomorrow but I follow your recommendation not to work with nested dockers.
We could also redesign our strategy when creating the docker for the JupyterHub and build an extended sos-notebook docker.
When I have something useful, I will come back to you - might take some weeks though since I am abroad for several business trips in the coming 3 weeks.

**Comment by vibbits** [comment]
Hi all, this issue can be closed. We have been able to install jupyterhub and sos next to each other on a fresh linux server at our university. All works fine. I'll play around with the docker installation and how we manage tools we would like to run in the SoS notebook.
