### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by luluperet** [vatlab/sos-notebook#79]
Hello,
is there autocomplete (tab) in sos notebook for each language please?

**Comment by BoPeng** [comment]
The problem here is that when `tab` is pressed from the frontend, no information on the cell is passed to the SoS kernel so it does not know the language of the cell. I have just submitted a patch that complete text according to the "current kernel". That is to say, if you run `%use R` then work in a R cell, autocompletion would work fine. Otherwise the text would still be completed as `SoS`.

Let me see if a complete solution is possible.

**Comment by BoPeng** [comment]
I have to pass cell kernel information to the kernel with each cell switch, but it is nice to have auto-completion work. Please let me know if it works for you (clone the repo, run `pip install . -U` to install).

**Comment by luluperet** [comment]
Hello, it works !!!!!
It's really nice, you are the best.
I love this notebook !
