### ISSUE TITLE
Sticky Kernel Setting

### ISSUE THREAD

**Issue by aolney** [vatlab/sos-notebook#95]
Currently SOS defaults to SOS kernel when new cells are created.

Ideally, the kernel type would be "sticky" and default to the kernel type in the preceding cell.

**Comment by BoPeng** [comment]
Your description is not entirely correct because SoS defaults to the "global default kernel", which can be changed from the menu bar, or with magic `%use`.

The "sticky" idea is very interesting though. If every new cell has the kernel of its previous cell, there is less a need for a global default and the workflow might be smoother. I am not quite sure what you meant by "preceding cell" though. There are two possibilities:

1. Previous evaluated cell. This basically merges magic `%use` and `%with` in the sense that evaluation of a cell will change the global default so that the new cell will have its kernel. It can be tricky if you evaluate a cell somewhere and insert a new cell in another location though.

2. The cell before the new cell. This behavior seems to be more consistent because any new cell will just get the kernel of its previous cell.  There is less a need for a global default language selector.

This is related to #81 so perhaps @luluperet and @gaow can comment.

**Comment by HenryLeongStat** [comment]
IMO, the second solution is better. 

Does it mean that `%use` magic will be deleted? Even though I prefer the 'sticky' kernel idea, we are not sure the other users' thoughts. Maybe some of them prefer the global setting with `%use`? Or we can come up a way to keep `%use` while we are implementing the `sticky` kernel idea.

**Comment by aolney** [comment]
Yes the 2nd option "cell before the new cell" is what I mean by preceding. This is the default behavior of Beaker, which I have used for several years, and I find that it is very effective.

**Comment by BoPeng** [comment]
I can appreciate the simplicity of the "follow the previous cell" approach. The `%use` and `%with` magics were designed before the language selectors were added to the frontend UI when a global default was needed to the control the kernel of a new cell. Let me see what it takes to implement the sticky behavior.

**Comment by BoPeng** [comment]
More testing is needed but here are what I have done so far:

1. Implement the new "sticky" behavior for new cells.
2. Remove the global language selector from UI and kernel messaging.
3. Change the behavior of magics `%with` and `%use`.

For the last item, the major difference between `%with` and `%use` was that the latter changes global default. Since this is no longer needed, I have separated the features between the two according to typical usages of the magics:

1. `%use` for the creation of new kernels with options such as `--kernel`, `--language`, and `--color`
2. `%with` for the evaluation of cell content with `--in` and `--out`

**Comment by aolney** [comment]
:+1:

**Comment by aolney** [comment]
I'm testing this in the jupyterlab-sos extension, and the behavior is correctly sticky.

However, one of the UI changes may create additional confusion, namely, the removal of the cell-level kernel menu.

Current behavior:

- Create a notebook using SoS kernel
- Set R kernel in first cell dropdown kernel menu, execute `x=3`
- In next cell execute `x`
- Call fails because default kernel is SoS
- Change default kernel to R
- In next cell execute `x`
- Call succeeds
- Change default kernel to F#
- In next cell execute `let y = 2`
- In next cell execute `y`
- Calls succeed

**Problem**: UI no longer shows kernel type of previously executed cells

**Possible solution**: keep dropdown kernel menu for each cell

![sos](https://user-images.githubusercontent.com/4432084/42044240-1736097c-7abe-11e8-84e9-b71bba80e433.png)

**Comment by BoPeng** [comment]
This is the sos-notebook repo and the changes were made only to sos-notebook. The jupyterlab extension has not been updated yet.

**Comment by BoPeng** [comment]
Moved to vatlab/jupyterlab-sos#18

**Comment by BoPeng** [comment]
@aolney I have implemented the sticky behavior on jupyterlab-sos and released jupyterlab-sos 0.1.7. Please test and let us know (create a ticket in jupyterlab-sos repo) if you notice any problem.
